2025-06-18 01:42:51,224 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {}
2025-06-19 15:57:56,229 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'txt': 'Mark as Aw', 'doctype': 'Workflow Action Master', 'ignore_user_permissions': '0', 'reference_doctype': 'Workflow Transition', 'page_length': '10', 'cmd': 'frappe.desk.search.search_link'}
2025-06-19 15:58:18,015 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'txt': 'Mark as Awaiting Payment', 'doctype': 'Workflow Action Master', 'ignore_user_permissions': '0', 'reference_doctype': 'Workflow Transition', 'page_length': '10', 'cmd': 'frappe.desk.search.search_link'}
2025-06-19 15:58:47,001 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'txt': 'Mark as Aw', 'doctype': 'Workflow Action Master', 'ignore_user_permissions': '0', 'reference_doctype': 'Workflow Transition', 'page_length': '10', 'cmd': 'frappe.desk.search.search_link'}
2025-06-19 16:00:02,944 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'txt': 'Mark as A', 'doctype': 'Workflow Action Master', 'ignore_user_permissions': '0', 'reference_doctype': 'Workflow Transition', 'page_length': '10', 'cmd': 'frappe.desk.search.search_link'}
2025-06-19 16:06:03,526 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'txt': 'Mark as A', 'doctype': 'Workflow Action Master', 'ignore_user_permissions': '0', 'reference_doctype': 'Workflow Transition', 'page_length': '10', 'cmd': 'frappe.desk.search.search_link'}
2025-06-20 22:46:17,358 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"docstatus":0,"doctype":"Module Def","name":"new-module-def-cpupgpkdhk","__islocal":1,"__unsaved":1,"owner":"Administrator","custom":0,"module_name":"coffee_roaster","app_name":"coffee_roaster"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-20 22:47:22,660 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"docstatus":0,"doctype":"Module Def","name":"new-module-def-vdprpskhdr","__islocal":1,"__unsaved":1,"owner":"Administrator","custom":0,"module_name":"coffee_roaster","app_name":"coffee_roaster"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-20 22:47:34,821 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"docstatus":0,"doctype":"Module Def","name":"new-module-def-vdprpskhdr","__islocal":1,"__unsaved":1,"owner":"Administrator","custom":0,"module_name":"coffee_roaster","app_name":"coffee_roaster"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-22 10:45:56,500 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"name":"d68sbf9cbr","owner":"Administrator","creation":"2025-06-22 10:07:25.559625","modified":"2025-06-22 10:07:25.559625","modified_by":"Administrator","docstatus":0,"idx":0,"sample_id":"062500001","status":"Draft","assessment_date":"2025-06-10","evaluator":"Administrator","moisture":0,"color":"Blue Green","total_cat_1_defects":0,"total_cat_2_defects":0,"total_defect_score":0,"passed_qc":1,"workflow_state":"Draft","doctype":"Green Bean Assessment","cat2_defects":[],"cat1_defects":[{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-ouiogckmej","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Black","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":1,"__unedited":false,"defect_count":6},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-rvlkxlhwta","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Sour","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":6},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-bypjlkzhfd","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Fungus Damage","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":3,"__unedited":false,"defect_count":7},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-cdeqimuthm","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Dried Cherry","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":4,"__unedited":false,"defect_count":8},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-lsjuxwvmmh","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Severe Insect Damage","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":5,"__unedited":false,"defect_count":8},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-wtwserzqaq","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Foreign Matter","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":6,"__unedited":false,"defect_count":14}],"__last_sync_on":"2025-06-22T07:44:39.830Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-22 10:51:34,664 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"name":"d68sbf9cbr","owner":"Administrator","creation":"2025-06-22 10:07:25.559625","modified":"2025-06-22 10:07:25.559625","modified_by":"Administrator","docstatus":0,"idx":0,"sample_id":"062500001","status":"Draft","assessment_date":"2025-06-10","evaluator":"Administrator","moisture":0,"color":"Blue Green","total_cat_1_defects":0,"total_cat_2_defects":0,"total_defect_score":0,"passed_qc":1,"workflow_state":"Draft","doctype":"Green Bean Assessment","cat2_defects":[],"cat1_defects":[{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-ouiogckmej","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Black","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":1,"__unedited":false,"defect_count":6},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-rvlkxlhwta","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Sour","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":6},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-bypjlkzhfd","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Fungus Damage","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":3,"__unedited":false,"defect_count":7},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-cdeqimuthm","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Dried Cherry","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":4,"__unedited":false,"defect_count":8},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-lsjuxwvmmh","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Severe Insect Damage","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":5,"__unedited":false,"defect_count":8},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-wtwserzqaq","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Foreign Matter","parent":"d68sbf9cbr","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":6,"__unedited":false,"defect_count":14}],"__last_sync_on":"2025-06-22T07:44:39.830Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-22 10:54:58,615 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"name":"7vdgqc1o8n","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":0,"sample_id":"062500004","status":"Draft","assessment_date":"2025-06-20","evaluator":"Administrator","origin":"har","bean_grade":"g1","moisture":67,"color":"Blue Green","total_cat_1_defects":0,"total_cat_2_defects":0,"total_defect_score":0,"passed_qc":0,"notes":null,"workflow_state":"Draft","doctype":"Green Bean Assessment","cat1_defects":[{"name":"7vdum4f628","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":1,"defect_type":"Full Black","defect_count":50,"full_defects":0,"parent":"7vdgqc1o8n","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","doctype":"Category 1 Defect Entry","__unsaved":1},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-ninkfhqtvd","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Sour","parent":"7vdgqc1o8n","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":6}],"cat2_defects":[{"name":"7vdh2fk2dh","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":1,"defect_type":"Partial Sour","defect_count":9,"full_defects":0,"parent":"7vdgqc1o8n","parentfield":"cat2_defects","parenttype":"Green Bean Assessment","doctype":"Category 2 Defect Entry","__unsaved":1},{"docstatus":0,"doctype":"Category 2 Defect Entry","name":"new-category-2-defect-entry-lefvvstcyf","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Partial Sour","parent":"7vdgqc1o8n","parentfield":"cat2_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":9}],"__last_sync_on":"2025-06-22T07:53:09.058Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-22 10:55:09,722 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'doc': '{"name":"7vdgqc1o8n","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":0,"sample_id":"062500004","status":"Draft","assessment_date":"2025-06-20","evaluator":"Administrator","origin":"har","bean_grade":"g1","moisture":67,"color":"Blue Green","total_cat_1_defects":0,"total_cat_2_defects":0,"total_defect_score":0,"passed_qc":0,"notes":null,"workflow_state":"Draft","doctype":"Green Bean Assessment","cat1_defects":[{"name":"7vdum4f628","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":1,"defect_type":"Full Black","defect_count":50,"full_defects":0,"parent":"7vdgqc1o8n","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","doctype":"Category 1 Defect Entry","__unsaved":1},{"docstatus":0,"doctype":"Category 1 Defect Entry","name":"new-category-1-defect-entry-ninkfhqtvd","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Full Sour","parent":"7vdgqc1o8n","parentfield":"cat1_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":6}],"cat2_defects":[{"name":"7vdh2fk2dh","owner":"Administrator","creation":"2025-06-22 10:53:08.510291","modified":"2025-06-22 10:53:08.510291","modified_by":"Administrator","docstatus":0,"idx":1,"defect_type":"Partial Sour","defect_count":9,"full_defects":0,"parent":"7vdgqc1o8n","parentfield":"cat2_defects","parenttype":"Green Bean Assessment","doctype":"Category 2 Defect Entry","__unsaved":1},{"docstatus":0,"doctype":"Category 2 Defect Entry","name":"new-category-2-defect-entry-lefvvstcyf","__islocal":1,"__unsaved":1,"owner":"Administrator","defect_type":"Partial Sour","parent":"7vdgqc1o8n","parentfield":"cat2_defects","parenttype":"Green Bean Assessment","idx":2,"__unedited":false,"defect_count":9}],"__last_sync_on":"2025-06-22T07:53:09.058Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-22 16:34:25,025 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'app_path': 'coffee-roaster'}
2025-06-22 16:34:25,034 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'app_path': 'coffee-roaster'}
2025-06-22 16:34:47,977 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'app_path': 'coffee-roaster'}
2025-06-22 19:01:52,961 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'sb_public_items': '[{"title":"Coffee Roaster All","parent_page":"","public":"1"},{"title":"Coffee Roaster","parent_page":"","public":"1"},{"title":"Home","parent_page":"","public":"1"},{"title":"Accounting","parent_page":"","public":"1"},{"title":"Payables","parent_page":"Accounting","public":"1"},{"title":"Receivables","parent_page":"Accounting","public":"1"},{"title":"Financial Reports","parent_page":"Accounting","public":"1"},{"title":"Buying","parent_page":"","public":"1"},{"title":"Selling","parent_page":"","public":"1"},{"title":"Stock","parent_page":"","public":"1"},{"title":"Assets","parent_page":"","public":"1"},{"title":"Manufacturing","parent_page":"","public":"1"},{"title":"Quality","parent_page":"","public":"1"},{"title":"CRM","parent_page":"","public":"1"},{"title":"Users","parent_page":"","public":"1"},{"title":"Website","parent_page":"","public":"1"},{"title":"Tools","parent_page":"","public":"1"},{"title":"ERPNext Settings","parent_page":"","public":"1"},{"title":"Integrations","parent_page":"","public":"1"},{"title":"ERPNext Integrations","parent_page":"","public":"1"},{"title":"Build","parent_page":"","public":"1"}]', 'sb_private_items': '[]', 'cmd': 'frappe.desk.doctype.workspace.workspace.sort_pages'}
2025-06-22 19:03:12,125 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'title': 'Coffee Roaster All', 'public': '1', 'new_widgets': '{"shortcut":[{"name":"shortcut-undefined-ptexJUUsZIecjvScckdo","label":"Green Bean Assessment","link_to":"Green Bean Assessment","doc_view":"List","color":"Grey","stats_filter":"[]","type":"DocType"}]}', 'blocks': '[{"id":"3fDJ_PD5Fh","type":"header","data":{"text":"<span class=\\"h4\\">Coffee Roaster All</span>","col":12}},{"id":"er6tmuw-Iv","type":"header","data":{"text":"<span class=\\"h4\\"><b>Quality</b></span>","col":12}},{"id":"p5_mGaZgcs","type":"shortcut","data":{"shortcut_name":"Green Bean Assessment","col":3}}]', 'cmd': 'frappe.desk.doctype.workspace.workspace.save_page'}
2025-06-22 19:04:51,712 ERROR frappe New Exception collected in error log
Site: coffeesite.local
Form Dict: {'title': 'Coffee Roaster All', 'public': '1', 'new_widgets': '{"shortcut":[{"name":"shortcut-undefined-CwlpfSDSmidiIcwQWaPH","label":"Green Bean Assessment","link_to":"Green Bean Assessment","doc_view":"List","color":"Grey","stats_filter":"[]","type":"DocType"}]}', 'blocks': '[{"id":"uDREc9Uhk6","type":"header","data":{"text":"<span class=\\"h4\\">Coffee Roaster All</span>","col":12}},{"id":"s8O_wvUYyG","type":"header","data":{"text":"<span class=\\"h4\\"><b>Quality</b></span>","col":12}},{"id":"7mpuDQVc8x","type":"shortcut","data":{"shortcut_name":"Green Bean Assessment","col":3}}]', 'cmd': 'frappe.desk.doctype.workspace.workspace.save_page'}
2025-06-23 00:43:13,112 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,158 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,173 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,217 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,227 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,284 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,310 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,316 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,346 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,401 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,417 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,419 ERROR frappe Could not take error snapshot: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/sime/coffee_bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,448 ERROR frappe Failed to run after request hook
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/sime/coffee_bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/sime/coffee_bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
2025-06-23 00:43:13,519 ERROR frappe Failed to run after request hook
Site: coffeesite.local
Form Dict: {}
Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/sime/coffee_bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/sime/coffee_bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/sime/coffee_bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/sime/coffee_bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1616, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sime/coffee_bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1585, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sime/coffee_bench/apps/frappe/frappe/__init__.py", line 1451, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py", line 2, in <module>
    from . import __version__ as app_version
ImportError: cannot import name '__version__' from partially initialized module 'coffee_roaster.hooks' (most likely due to a circular import) (/home/sime/coffee_bench/apps/coffee_roaster/coffee_roaster/hooks/__init__.py)
